version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - my-network


  customerservice:
    build:
      context: ./Customers
      dockerfile: Dockerfile
    image: "customerservice"
    container_name: customerservice
    restart: "on-failure"
    ports:
      - "5555:5555"
    depends_on:
      - mongodb
    networks:
      - my-network

      
  feedbackservice:
    build:
      context: ./Feedbacks
      dockerfile: Dockerfile
    image: "feedbackservice"
    container_name: feedbackservice
    restart: "on-failure"
    ports:
      - "4545:4545"
    depends_on:
      - mongodb
    networks:
      - my-network



  reclamationservice:
    build:
      context: ./Reclamations
      dockerfile: Dockerfile
    image: "reclamationservice"
    container_name: reclamationservice
    restart: "on-failure"
    ports:
      - "7777:7777"
    depends_on:
      - mongodb
    networks:
      - my-network
networks:
  my-network:





      
